### ISSUE TITLE
How can i clear the selections by javascript

### ISSUE THREAD

**Issue by Checkson** [claviska/jquery-selectable#4]
Hello! Thanks for your nice plugin, I have read the source code and there seemed to be no way to clear the contents of the selection

**Comment by claviska** [comment]
Sure, see the methods section for more details. It looks like this:

```js
$('.my-list').selectable('selectNone');
```

**Comment by Checkson** [comment]
Oh sorry, I found it! And I doubt that I was blind at that time. Thanks again!
